language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -v --testsuite=unit

after_success:
  - travis_retry php ./vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
    - php: nightly


notifications:
  email:
    recipients:
    - oleksii.mylotskyi@milsdev.com
    on_success: never
    on_failure: always

fast_finish: true
