language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -v --testsuite=unit

after_script:
  - ./vendor/bin/coveralls -v --exclude-no-stmt

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6


notifications:
  email:
    recipients:
    - oleksii.mylotskyi@milsdev.com
    on_success: never
    on_failure: always

fast_finish: true
